@startuml
title: Provisioning phase
skinparam BackgroundColor transparent

skinparam componentStyle rectangle
component cluster-api-provider-metal3 as capm3 {
   component "Metal3Machine"
}
component "Baremeta Operator" as bmo {
   component "BareMetalHost"
   note as notebmo
    - bootMACAddress(BMC)
    - IP address    
    - server credentials
    - Hardware details [cpu,disk,…]
    - image
    - cloud-init data 
  end note
  BareMetalHost .. notebmo
}
component Ironic as ironic {
   component “Node Information" as nodeinfo
}
component "Bare metal Server" as server {
   component "Bare metal Server" as bms
   note as noteserver
    - Ubuntu 20.04
    - cloud-init data
  end note
  bms .. noteserver
}
Metal3Machine -> BareMetalHost
BareMetalHost -> ironic
nodeinfo -> bms
@enduml