apiVersion: ironic.metal3.io/v1alpha1
kind: Ironic
metadata:
  name: ironic
  namespace: baremetal-operator-system
spec:
  networking:
    dhcp:
      rangeBegin: "192.168.222.100"
      rangeEnd: "192.168.222.200"
      networkCIDR: "192.168.222.0/24"
    interface: "eth0"
    ipAddress: "192.168.222.2"
    ipAddressManager: "keepalived"
