@startuml
title: Cluster API - full flow
skinparam BackgroundColor transparent

participant User as User
participant "CAPI Provider Metal3" as CAPM3
participant "BareMetal Operator" as BMO
participant Ironic as Ironic
participant "Physical Server" as Server

group "Inspection"
User -> BMO: Create BareMetalHost
BMO -> Ironic: Create a Node
BMO -> Ironic: Start Inspection
Ironic -> Server: Boot the service ramdisk
Server -> Ironic: Send back hardware details
Ironic -> BMO: Success!
BMO -> Ironic: Fetch hardware details

group "Machine Provisioning"
User -> CAPM3: Create Metal3Machine
CAPM3 <-> BMO: Pick a suitable BareMetalHost
CAPM3 -> BMO: Populate image and user data
BMO -> Ironic: Start Provisioning
Ironic -> Server: Clean the disks
Ironic -> Server: Start Provisioning
Server -> Ironic: Fetch image
Ironic -> Server: Reboot into instance
Ironic -> BMO: Success!
BMO -> CAPM3: Success!
@enduml
