name: Test Quick Start Guide

on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: "ubuntu-latest"
      ref:
        type: string
        default: ${{ github.ref }}
      timeout-minutes:
        type: number
        default: 90

permissions: {}

jobs:
  test:
    name: Quick Start Test
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
    timeout-minutes: ${{ inputs.timeout-minutes }}

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        ref: ${{ inputs.ref }}
        persist-credentials: false

    - name: Install libvirt
      run: |
        sudo apt-get update
        sudo apt-get install -y libvirt-daemon-system qemu-kvm virt-manager libvirt-dev

    - name: Run Quick Start Test
      # We need a new shell to pick up the new group. That is why we do the sudo -s -u "${USER}"  ...
      # Remove the pre-installed go version. We install the exact version we need.
      run: |
        sudo usermod -a -G libvirt "${USER}"
        sudo -s -u "${USER}"  --preserve-env bash ${{ github.workspace }}/hack/quick-start/quick-start-test.sh
